[package]
name = "untitled"
version = "0.1.0"
edition = "2021"
authors = ["Mikhail Zharkov zharkovma00@mail.ru"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
